AWSTemplateFormatVersion: 2010-09-09
Description: >
  Olawale Akin-Odanye / Better cloud cloud architecture

Parameters: 
  EnvironmentName:
    Type: String
    Description: Name to be used to identify resources from this stack
  vpcCIDR:
    Type: String
    Description: VPC CidrBlock of the private
  PublicSubnet1CIDR:
    Type: String
    Description: CIDR block for the public subnet in availability zone 1
  PublicSubnet2CIDR:
    Type: String
    Description: CIDR block for the public subnet in availability zone 2
  WebSubnetPrivCIDR1:
    Type: String
    Description: CIDR block for the web private subnet in availability zone 1
  WebSubnetPrivCIDR2:
    Type: String
    Description: CIDR block for the web private subnet in availability zone 2
  AppSubnetPrivCIDR1:
    Type: String
    Description: CIDR block for application web private subnet in availability zone 1
  AppSubnetPrivCIDR2:
    Type: String
    Description: CIDR block for application web private subnet in availability zone 2
  DBSubnetPrivCIDR1:
    Type: String
    Description: CIDR block for database private subnet in availability zone 1
  DBSubnetPrivCIDR2:
    Type: String
    Description: CIDR block for database private subnet in availability zone 2

  
Resources:
# General VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref vpcCIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC

  VpcGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC-Gateway

  VpcAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref VpcGateway
      VpcId: !Ref VPC
  
  # Availabiliy Zone 1
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PUB-SUB-1

  WebSubnetPRIV1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref WebSubnetPrivCIDR1
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}--WEB-SUB-1

  AppSubnetPRIV1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref AppSubnetPrivCIDR1
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-APP-SUB-1

  DBSubnetMainPRIV1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref DBSubnetPrivCIDR1
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-DB-SUB-1
  
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: VpcAttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-NAT-EIP-1

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt [NatGateway1EIP, AllocationId]
      SubnetId: !Ref PublicSubnet1

  # Availability Zone 2
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PUB-SUB-2


  WebSubnetPRIV2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref WebSubnetPrivCIDR2
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}--WEB-SUB-2


  AppSubnetPRIV2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref AppSubnetPrivCIDR2
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-APP-SUB-2


  DBSubnetReplicaPRIV2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref DBSubnetPrivCIDR2
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-DB-SUB-2

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: VpcAttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-NAT-EIP-2

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt [NatGateway2EIP, AllocationId]
      SubnetId: !Ref PublicSubnet2

Outputs:  
  VpcOut:
    Description: VPC id of the network stack
    Values: !Ref VPC
    Export:
      Name: !Sub ${EnvironmentName}-VPC

  PublicSubnetOut1:
    Description: ID of the public subnet in AZ1
    Values: !Ref PublicSubnet1
    Export:
      Name: !Sub ${EnvironmentName}-PUB-NET-1

  PublicSubnetOut2:
    Description: ID of the public subnet in AZ2
    Values: !Ref PublicSubnet2
    Export:
      Name: !Sub ${EnvironmentName}-PUB-NET-2

  PublicSubnets:
    Description: A list of all the public subnets
    Values: !Join [",", [!Ref PublicSubnet1, !Ref PublicSubnet2]]
    Export:
      Name: !Sub ${EnvironmentName}-PUB-NETS

  WebSubnet1:
    Description: ID of the private web subnet in AZ1
    Values: !Ref WebSubnetPRIV1
    Export:
      Name: !Sub ${EnvironmentName}-WEB-1

  WebSubnet2:
    Description: ID of the private web subnet in AZ2
    Values: !Ref WebSubnetPRIV2
    Export:
      Name: !Sub ${EnvironmentName}-WEB-1

  WebSubnets:
    Description: A list of private web subnets
    Values: !Join [",", [!Ref WebSubnetPRIV1, !Ref WebSubnetPRIV2]]
    Export:
      Name: !Sub ${EnvironmentName}-WEBS

  DBSubnet1:
    Description: ID of the private db subnet in AZ1
    Values: !Ref DBSubnetMainPRIV1
    Export:
      Name: !Sub ${EnvironmentName}-DB-1

  DBSubnet2:
    Description: ID of the private db subnet in AZ2
    Values: !Ref DBSubnetMainPRIV2
    Export:
      Name: !Sub ${EnvironmentName}-DB-2

  DBSubnets:
    Description: A list of private db subnets
    Values: !Join [",", [!Ref DBSubnetMainPRIV1, !Ref DBSubnetMainPRIV2]]
    Export:
      Name: !Sub ${EnvironmentName}-DBS

  AppSubnet1:
    Description: ID of the private application subnet in AZ1
    Values: !Ref AppSubnetPRIV1
    Export:
      Name: !Sub ${EnvironmentName}-APP-1

  AppSubnet2:
    Description: ID of the private applicatino subnet in AZ2
    Values: !Ref AppSubnetPRIV2
    Export:
      Name: !Sub ${EnvironmentName}-APP-2

  AppSubnets:
    Description: A list of private application subnets
    Values: !Join [",", [!Ref AppSubnetPRIV1, !Ref AppSubnetPRIV2]]
    Export:
      Name: !Sub ${EnvironmentName}-APPS

